
DECLARE @mm numeric,@aa numeric,@fec_proc varchar(5),@fec_ini varchar(5),@mes varchar(3), @anioo varchar(5)


--set @mm=04
--set @mm='#mes#'
set @mes='#mes#'
set @anioo='#annio#'


IF (@mes='01')
BEGIN 
SET @mm=01
END

IF (@mes='02')
BEGIN 
SET @mm=02
END

IF (@mes='03')
BEGIN 
SET @mm=03
END

IF (@mes='04')
BEGIN 
SET @mm=04
END

IF(@mes='05')
BEGIN
SET @mm=05
END

IF (@mes='06')
BEGIN 
SET @mm=06
END

IF (@mes='07')
BEGIN 
SET @mm=07
END

IF (@mes='08')
BEGIN 
SET @mm=08
END

IF (@mes='09')
BEGIN 
SET @mm=09
END

IF (@mes='10')
BEGIN 
SET @mm=10
END

IF (@mes='11')
BEGIN 
SET @mm=11
END

IF (@mes='12')
BEGIN 
SET @mm=12
END
--set @aa=2016
--set @aa='#annio#'

IF(@anioo='14')
BEGIN
SET @aa=2014
END

IF(@anioo='15')
BEGIN
SET @aa=2015
END

IF(@anioo='16')
BEGIN
SET @aa=2016
END

IF(@anioo='17')
BEGIN
SET @aa=2017
END

IF(@anioo='18')
BEGIN
SET @aa=2018
END

IF(@anioo='19')
BEGIN
SET @aa=2019
END

set @fec_proc='#proceso#'
--set @fec_proc='1604'
set @fec_ini='#aniomesprim#'
--set @fec_ini='1601'



IF OBJECT_ID (N'dbo.BASE_ASES_EFECT') IS NOT NULL
DROP TABLE dbo.BASE_ASES_EFECT;


IF OBJECT_ID (N'dbo.BASE_ASES_EFECT_DOS') IS NOT NULL
DROP TABLE dbo.BASE_ASES_EFECT_DOS;

IF OBJECT_ID (N'dbo.PRIMERA_ETAPA_REPORTA', N'U') IS NOT NULL
DROP TABLE dbo.PRIMERA_ETAPA_REPORTA;

IF OBJECT_ID (N'dbo.DETALLE_EFECTIVIDAD_REPORTE_UNO', N'U') IS NOT NULL
DROP TABLE dbo.DETALLE_EFECTIVIDAD_REPORTE_UNO;

IF OBJECT_ID (N'dbo.DIR_MES_A_MES_TA', N'U') IS NOT NULL
DROP TABLE dbo.DIR_MES_A_MES_TA;

IF OBJECT_ID (N'DIR_ACUMULAD_TA', N'U') IS NOT NULL
DROP TABLE dbo.DIR_ACUMULAD_TA;

IF OBJECT_ID (N'dbo.FUNCI_MES_A_MES_TA', N'U') IS NOT NULL
DROP TABLE dbo.FUNCI_MES_A_MES_TA;

IF OBJECT_ID (N'dbo.MAT_MES_A_MES_TA', N'U') IS NOT NULL
DROP TABLE dbo.MAT_MES_A_MES_TA;

IF OBJECT_ID (N'dbo.SUC_MES_A_MES_TA', N'U') IS NOT NULL
DROP TABLE dbo.SUC_MES_A_MES_TA;

IF OBJECT_ID (N'dbo.OFNA_MES_A_MES_TA', N'U') IS NOT NULL
DROP TABLE dbo.OFNA_MES_A_MES_TA;

IF OBJECT_ID (N'dbo.DETALLE_PARA_OFNA', N'U') IS NOT NULL
DROP TABLE dbo.DETALLE_PARA_OFNA;

IF OBJECT_ID (N'dbo.MES_A_MES_TA', N'U') IS NOT NULL
DROP TABLE dbo.MES_A_MES_TA;

IF OBJECT_ID (N'dbo.HISTORIATA_PASO', N'U') IS NOT NULL
DROP TABLE dbo.HISTORIATA_PASO;

IF OBJECT_ID (N'dbo.MESES_ACUMULADOS_EFEC') IS NOT NULL
DROP TABLE dbo.MESES_ACUMULADOS_EFEC;

IF OBJECT_ID (N'dbo.FUNCI_ACUM_TA') IS NOT NULL
DROP TABLE dbo.FUNCI_ACUM_TA;

IF OBJECT_ID (N'dbo.MAT_ACUM_TA') IS NOT NULL
DROP TABLE dbo.MAT_ACUM_TA;

IF OBJECT_ID (N'dbo.SUC_ACUM_TA') IS NOT NULL
DROP TABLE dbo.SUC_ACUM_TA;

IF OBJECT_ID (N'dbo.OFNA_ACUM_TA') IS NOT NULL
DROP TABLE dbo.OFNA_ACUM_TA;

IF OBJECT_ID (N'dbo.P_RESP_GEREN') IS NOT NULL
	DROP TABLE dbo.P_RESP_GEREN;
	
IF OBJECT_ID (N'dbo.P_RESP_GERE2') IS NOT NULL
DROP TABLE dbo.P_RESP_GERE2;

IF OBJECT_ID (N'dbo.EDAS_SEMESTRE') IS NOT NULL
DROP TABLE dbo.EDAS_SEMESTRE

IF OBJECT_ID (N'dbo.REPETIDOS_TA') IS NOT NULL
DROP TABLE dbo.REPETIDOS_TA

/*DESMARCANDO 'CUMPLE TA MES ACTUAL' PARA LOS ASESORES INACTIVOS*/



/*DELETE FROM HISTORIATA WHERE PROCESO=@fec_proc

SELECT CALCULO,AGENTE,RecorrimientoAnual,
[GANADOR MES] = CASE 
WHEN PremioTotal>0 THEN 1
ELSE 0
END,
Proceso
INTO HISTORIATA_PASO
FROM Premios_asesores_training_2016 WHERE Proceso=@fec_proc AND RecorrimientoAnual<13
 
INSERT INTO HISTORIATA (CALCULO,AGENTE,RecorrimientoAnual,[GANADOR MES],PROCESO) SELECT CALCULO,AGENTE,RecorrimientoAnual,[GANADOR MES],PROCESO FROM HISTORIATA_PASO 
*/
/*REFERENCIAS CRUZADAS*/

IF OBJECT_ID (N'dbo.HISTORIATA_MATRIZ', N'U') IS NOT NULL
DROP TABLE dbo.HISTORIATA_MATRIZ;

SELECT AGENTE,[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]
INTO HISTORIATA_MATRIZ
FROM 
(SELECT AGENTE,RECORRIMIENTOANUAL,[GANADOR MES]FROM HISTORIATA)  AS p
PIVOT
(
SUM([GANADOR MES])
FOR RECORRIMIENTOANUAL IN
([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12])
) as PivotTable

/**********************************************************/
/**********************************************************/

SELECT DISTINCT(A.AGENTE) 
INTO BASE_ASES_EFECT
FROM Premios_asesores_training_2016 A 
WHERE (A.Proceso>=@fec_ini AND A.Proceso<=@fec_proc)  AND (A.RecorrimientoAnual>=1 AND A.RecorrimientoAnual<=6) /*AND  A.AGENTE in (SELECT NUM_AGENTE FROM C_PILOTOS)*/


SELECT A.AGENTE,B.FechaInicioConcurso AS CONCURSO,B.PremioTotal
INTO BASE_ASES_EFECT_DOS
FROM BASE_ASES_EFECT A LEFT OUTER JOIN Premios_asesores_training_2016 B ON A.AGENTE=B.AGENTE AND B.Proceso=@fec_proc
/*************************/



/*PONER FECHA DE CONCURSO A LOS ASESORES QUE TENGAN MÁS DE 12 MESES*/
UPDATE A SET A.CONCURSO=B.CONCURSO FROM BASE_ASES_EFECT_DOS A INNER JOIN AGENTES B ON A.AGENTE=B.NUM_AGENTE AND (B.Proceso=@fec_proc) WHERE A.CONCURSO IS NULL

/**/
/*UPDATE BASE_ASES_EFECT_DOS SET CONCURSO='2016-12-19' WHERE AGENTE=72232
UPDATE BASE_ASES_EFECT_DOS SET CONCURSO='2016-12-15' WHERE AGENTE=72609
UPDATE BASE_ASES_EFECT_DOS SET CONCURSO='2016-09-29' WHERE AGENTE=70608
UPDATE BASE_ASES_EFECT_DOS SET CONCURSO='2016-12-15' WHERE AGENTE=72338
UPDATE BASE_ASES_EFECT_DOS SET CONCURSO='2016-12-19' WHERE AGENTE=71976
UPDATE BASE_ASES_EFECT_DOS SET CONCURSO='2016-12-20' WHERE AGENTE=72221
*/
/**/
SELECT A.AGENTE,C.DESC_VTA,C.DESC_OFNA,C.DESC_GEREN,B.PROM AS PROM_SUC,C.PROM_MAT,
C.RAZ_SOCIAL,C.NOMBRE_SUC,B.NUM_AGENTE,B.NOMBRE_DEL,B.FECHA_DE_C,A.CONCURSO,B.GRUPO,
MESES_ANO=CASE
WHEN YEAR(A.CONCURSO)<>@aa-1 THEN 0
ELSE
12-MONTH(A.CONCURSO)+1
END,
GANA_MES_ACTUAL=CASE WHEN A.PremioTotal>0
THEN 1
ELSE 0
END,
D.[1],
D.[2],
D.[3],
D.[4],
D.[5],
D.[6]
INTO PRIMERA_ETAPA_REPORTA
FROM BASE_ASES_EFECT_DOS A INNER JOIN ASESORES_PREMIOS B ON A.AGENTE=B.NUM_AGENTE AND B.Proceso=@fec_proc
INNER JOIN CATALOGO C ON B.PROM=C.PROM_SUC AND C.Proceso=@fec_proc
INNER JOIN HISTORIATA_MATRIZ D ON A.AGENTE=D.AGENTE   

/********************************************/
/*****************AJUSTES********************/
SELECT NOMBRE_DEL , COUNT(NOMBRE_DEL) AS REPETIDO INTO REPETIDOS_TA FROM PRIMERA_ETAPA_REPORTA GROUP BY NOMBRE_DEL ORDER BY REPETIDO DESC

ALTER TABLE PRIMERA_ETAPA_REPORTA ADD REPETIDO NVARCHAR(1)

UPDATE PRIMERA_ETAPA_REPORTA   SET REPETIDO = '*' 
FROM PRIMERA_ETAPA_REPORTA A INNER JOIN REPETIDOS_TA B ON A.NOMBRE_DEL = B.NOMBRE_DEL 
WHERE B.REPETIDO>1 AND A.GRUPO <> 2

DELETE FROM PRIMERA_ETAPA_REPORTA WHERE REPETIDO = '*'

DELETE FROM PRIMERA_ETAPA_REPORTA WHERE AGENTE IN (82001,79511,78118,77508,80356)

/*DELETE FROM PRIMERA_ETAPA_REPORTA WHERE AGENTE IN (75744,76523,78898,79226,78898,76523,78118,78320,75586,77508,75771,77697,75272,77175,77754,77518,77574,77613,74830,74255,77192,73684,73460,74433,77175,77028,73241,73658,76647,76685,76787,73196,76751,73998,76710,76632,73928,73221,76385,76257,76262,73258,76016,76072,72607,74483,72155,75589,75800,73373,71684,72050,72759,74998,75002,75100,75344,75437,71568,72849,72091,72711,74759,71975,71883,74626,74656,74700,74912,73403,71867,72398,74837,74724,74633,7461572398,71412,71509,71800,72007,74027,74112,74150,70788,72060,71201,71609,70891,71518,73477,73646,73661,73481,70275,73110,73157,73206,73210,73232,73279,70248,72903,68153,70028,72931,72966,73023,69749,69032,69114,69473,69652,69826,70390,70453,71272,71334,71474,71505,71563,71606,71978,72223,72366,72551,72681,71336,71495,71540,71571,72034,69567,72353,72339,69295,68877,71772,71146,69311,67754,68105,66801,69744,67366,66575,67108,65735,64931,65793,67235,65973,65994,67329,68930,65780,67751,67772,68190,66596,66233,66237,66315,66411,66476,66598,66786,67123,67178,67219,67363,67517,67537,68223,68525,68791,68825,68828,68943,69021,69142,69156,66168,66607,69954,68062,67412,67239,67973,68516,69422,69435,69557,69574,69578,69738,69759,70228,70315,70338,70373,70401,70487,70583,70668,71005,70915,68485,70983)*/

/*DELETE FROM PRIMERA_ETAPA_REPORTA WHERE AGENTE = 74837 AND MESES_ANO =0 */

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 where AGENTE=75190

UPDATE PRIMERA_ETAPA_REPORTA SET [3]=0 WHERE AGENTE=71360

UPDATE PRIMERA_ETAPA_REPORTA SET [5]=1 WHERE AGENTE=71501

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=72658

/*UPDATE PRIMERA_ETAPA_REPORTA SET [5]=0 WHERE AGENTE=71341*/

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=72286

UPDATE PRIMERA_ETAPA_REPORTA SET [3]=1 WHERE AGENTE=71414

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=72052

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=0 WHERE AGENTE=70415

UPDATE PRIMERA_ETAPA_REPORTA SET [3]=1 WHERE AGENTE=71344

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=71158

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=72610

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=0 WHERE AGENTE=73219

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=70975

/*UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=73214*/
UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=72356
UPDATE PRIMERA_ETAPA_REPORTA SET [4]=0 WHERE AGENTE=72480

/*CASO EVELIN SANTANA DOP*/
UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=72480
/**/

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=72039

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=73649

UPDATE PRIMERA_ETAPA_REPORTA SET [3]=1 WHERE AGENTE=72898

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=73572

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=74929

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=74957
UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=74957

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE= 76625

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=79249


UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=80306

/*UPDATE PRIMERA_ETAPA_REPORTA SET [1]=0 WHERE AGENTE=73658
UPDATE PRIMERA_ETAPA_REPORTA SET [1]=0 WHERE AGENTE=73073
UPDATE PRIMERA_ETAPA_REPORTA SET [1]=0 WHERE AGENTE=73172
UPDATE PRIMERA_ETAPA_REPORTA SET [1]=0 WHERE AGENTE=73729
UPDATE PRIMERA_ETAPA_REPORTA SET [1]=0 WHERE AGENTE=73766
UPDATE PRIMERA_ETAPA_REPORTA SET [4]=0 WHERE AGENTE=72350
UPDATE PRIMERA_ETAPA_REPORTA SET [1]=0 WHERE AGENTE=73767
UPDATE PRIMERA_ETAPA_REPORTA SET [4]=0 WHERE AGENTE=72516
UPDATE PRIMERA_ETAPA_REPORTA SET [4]=0 WHERE AGENTE=73134
*/

UPDATE PRIMERA_ETAPA_REPORTA SET [3]=0 WHERE AGENTE=72640
UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=73752

UPDATE PRIMERA_ETAPA_REPORTA SET [5]=1 WHERE AGENTE=71642

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=76024

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=71663

UPDATE PRIMERA_ETAPA_REPORTA SET [6]=1 WHERE AGENTE=73638

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=76255

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=76133

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=77917

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=79375

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=77411

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=78266


UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=79483

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=77846

UPDATE PRIMERA_ETAPA_REPORTA SET [3]=1 WHERE AGENTE=76847

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=78241

UPDATE PRIMERA_ETAPA_REPORTA SET [5]=1 WHERE AGENTE=79525

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=77641

UPDATE PRIMERA_ETAPA_REPORTA SET [6]=1 WHERE AGENTE=75936

UPDATE PRIMERA_ETAPA_REPORTA SET [5]=1 WHERE AGENTE=77296

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=78552

UPDATE PRIMERA_ETAPA_REPORTA SET [5]=1 WHERE AGENTE=78427

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=80304

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=80260

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=77211

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=81741

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=81741

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=81741

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=82565

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=82565

UPDATE PRIMERA_ETAPA_REPORTA SET [3]=1 WHERE AGENTE=82565

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=82462

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=82462

UPDATE PRIMERA_ETAPA_REPORTA SET [3]=1 WHERE AGENTE=82462

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=82714

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=82714

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=77211

/*UPDATE PRIMERA_ETAPA_REPORTA SET [4] = NULL WHERE AGENTE=74735
UPDATE PRIMERA_ETAPA_REPORTA SET [5] = NULL WHERE AGENTE=74735*/

/*UPDATE PRIMERA_ETAPA_REPORTA SET [1]=0 WHERE AGENTE=73885*/

/*UPDATE PRIMERA_ETAPA_REPORTA SET [6]=1 WHERE AGENTE=66594

UPDATE PRIMERA_ETAPA_REPORTA SET [1]=1 WHERE AGENTE=70122

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=69128

UPDATE PRIMERA_ETAPA_REPORTA SET GRUPO='2' WHERE NUM_AGENTE= 69054

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=69054

UPDATE PRIMERA_ETAPA_REPORTA SET [2]=1 WHERE AGENTE=71340*/

/*UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=70900

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=70534

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=70889

+
UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=71079

UPDATE PRIMERA_ETAPA_REPORTA SET [4]=1 WHERE AGENTE=70920*/
/*********************************************/

/********************************/

/*GENERANDO LA TABLA DEFINITIVA*/
SELECT A.DESC_VTA,A.DESC_OFNA,A.DESC_GEREN,A.PROM_SUC,A.PROM_MAT,A.RAZ_SOCIAL,A.NOMBRE_SUC,
A.NUM_AGENTE,A.NOMBRE_DEL,A.FECHA_DE_C,A.CONCURSO,A.GRUPO,
MESES_ANO,
MES_ACTUAL=CASE
WHEN MESES_ANO>0
THEN MESES_ANO+@mm
ELSE (@mm-MONTH(A.CONCURSO))+1
END,
A.[1],A.[2],
A.[3],A.[4],A.[5],A.[6],
ENE=0,FEB=0,MAR=0,ABR=0,MAY=0,JUN=0,JUL=0,
AGO=0,SEP=0,OCT=0,NOV=0,DIC=0,
MESES_GANADOS=0,
MESES_TOTALES=CASE 
WHEN MESES_ANO>0 
THEN 6-MESES_ANO
ELSE (@mm-MONTH(A.CONCURSO))+1
END
INTO DETALLE_EFECTIVIDAD_REPORTE_UNO
FROM PRIMERA_ETAPA_REPORTA A

/*******************************************/

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1] =0 WHERE [1] IS NULL

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [2] =0 WHERE [2] IS NULL

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [3] =0 WHERE [3] IS NULL

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [4] =0 WHERE [4] IS NULL

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [5] =0 WHERE [5] IS NULL

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [6] =0 WHERE [6] IS NULL

/********************************************/


UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= 0 WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=1
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= 0,[2]=0 WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=2
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= 0,[2]=0,[3]=0 WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=3
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= 0,[2]=0,[3]=0,[4]=0 WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=4
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= 0,[2]=0,[3]=0,[4]=0,[5]=0 WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=5

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET MESES_GANADOS=[1]+[2]+[3]+[4]+[5]+[6] 

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= NULL WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=1
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= NULL,[2]=NULL WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=2
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= NULL,[2]=NULL,[3]=NULL WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=3
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= NULL,[2]=NULL,[3]=NULL,[4]=NULL WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=4
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]= NULL,[2]=NULL,[3]=NULL,[4]=NULL,[5]=NULL WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=5

/**********************************************/

ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN [1] NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN [2] NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN [3] NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN [4] NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN [5] NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN [6] NVARCHAR

/***********************************************/

ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN ENE NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN FEB NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN MAR NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN ABR NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN MAY NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN JUN NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN JUL NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN AGO NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN SEP NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN OCT NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN NOV NVARCHAR
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ALTER COLUMN DIC NVARCHAR

/*************************************************/

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]='p' WHERE [1]='1'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [1]='i' WHERE [1]='0'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [2]='p' WHERE [2]='1'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [2]='i' WHERE [2]='0'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [3]='p' WHERE [3]='1'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [3]='i' WHERE [3]='0'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [4]='p' WHERE [4]='1'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [4]='i' WHERE [4]='0'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [5]='p' WHERE [5]='1'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [5]='i' WHERE [5]='0'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [6]='p' WHERE [6]='1'
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET [6]='i' WHERE [6]='0'

/*********************************************/

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ENE =NULL,FEB=NULL,MAR=NULL,ABR=NULL,MAY=NULL,JUN=NULL,JUL=NULL,AGO=NULL,SEP=NULL,OCT=NULL,NOV=NULL,DIC=NULL


/*********************************************/

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ENE = [6] WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=5
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ENE = [5],FEB=[6] WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=4
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ENE = [4],FEB=[5],MAR=[6] WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=3
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ENE = [3],FEB=[4],MAR=[5],ABR=[6] WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=2
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ENE = [2],FEB=[3],MAR=[4],ABR=[5],MAY=[6] WHERE YEAR(CONCURSO)<@aa AND MESES_ANO=1

/**********************************************/

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ENE = [1],FEB=[2],MAR=[3],ABR=[4],MAY=[5],JUN=[6] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=1
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET FEB = [1],MAR=[2],ABR=[3],MAY=[4],JUN=[5],JUL=[6] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=2
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET MAR = [1],ABR=[2],MAY=[3],JUN=[4],JUL=[5],AGO=[6] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=3
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ABR = [1],MAY=[2],JUN=[3],JUL=[4],AGO=[5],SEP=[6] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=4
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET MAY = [1],JUN=[2],JUL=[3],AGO=[4],SEP=[5],OCT=[6] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=5
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET JUN = [1],JUL=[2],AGO=[3],SEP=[4],OCT=[5],NOV=[6] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=6
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET JUL = [1],AGO=[2],SEP=[3],OCT=[4],NOV=[5],DIC=[6] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=7
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET AGO = [1],SEP=[2],OCT=[3],NOV=[4],DIC=[5] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=8
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET SEP = [1],OCT=[2],NOV=[3],DIC=[4] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=9
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET OCT = [1],NOV=[2],DIC=[3] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=10
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET NOV = [1],DIC=[2] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=11
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET DIC = [1] WHERE YEAR(CONCURSO)=@aa AND MONTH(CONCURSO)=12


/*AJUSTE*/
/*UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET NOV = NULL, DIC=NULL WHERE NUM_AGENTE=74735
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET OCT = NULL, NOV = NULL, DIC=NULL WHERE NUM_AGENTE=74188*/


UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ENE = NULL WHERE NUM_AGENTE=74735
UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET ENE = NULL WHERE NUM_AGENTE=74188

/*****ASIGNACIONES DE EDAS*****/
ALTER TABLE DETALLE_EFECTIVIDAD_REPORTE_UNO ADD EDA NVARCHAR(60)

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET EDA = B.EDA FROM DETALLE_EFECTIVIDAD_REPORTE_UNO A INNER JOIN ASIGNACION B ON A.NUM_AGENTE = B.ASESOR

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET EDA='LUIS JORGE GOMEZ' WHERE DESC_OFNA = 'PUEBLA' 

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET EDA='CARLOS ENRIQUE ROSALES CHAVEZ' WHERE DESC_OFNA = 'MERIDA' OR DESC_OFNA = 'VILLAHERMOSA'

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET EDA='ROMAN MANUEL CUEVAS JARAMILLO' WHERE DESC_OFNA = 'OAXACA' OR DESC_OFNA = 'VERACRUZ' OR DESC_OFNA = 'CUERNAVACA'

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET EDA='GABRIELA SILVA' WHERE DESC_OFNA = 'QUERETARO' OR DESC_OFNA = 'TOLUCA'

UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET EDA='NO ASIGNADO' WHERE DESC_VTA NOT LIKE '%Z%' AND EDA IS NULL

/**/



/***********************************************/
/*UPDATE DETALLE_EFECTIVIDAD_REPORTE_UNO SET MES_ACTUAL=6 WHERE MES_ACTUAL>6*/
/***********************************************/

/*ACTUALIZANDO LA TABLA PARA SACAR EL RESUMEN POR CIUDAD*/
SELECT * INTO DETALLE_PARA_OFNA FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 

/*UPDATE DETALLE_PARA_OFNA SET DESC_OFNA=DESC_GEREN WHERE DESC_VTA  NOT LIKE '%Z%'*/

/*UPDATE DETALLE_PARA_OFNA SET DESC_OFNA='MEXICO' WHERE DESC_GEREN LIKE '%MEXICO%' AND DESC_VTA  NOT LIKE '%Z%'
UPDATE DETALLE_PARA_OFNA SET DESC_OFNA='GUADALAJARA' WHERE DESC_GEREN LIKE '%GUADALAJARA%' AND DESC_VTA  NOT LIKE '%Z%'
UPDATE DETALLE_PARA_OFNA SET DESC_OFNA='MONTERREY' WHERE DESC_GEREN LIKE '%MONTERREY%' AND DESC_VTA  NOT LIKE '%Z%'*/

/*MES A MES TA*/


SELECT DESC_VTA,SUM (CASE WHEN MES_ACTUAL=1 AND ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN MES_ACTUAL=1 AND ENE='i' THEN 1 ELSE 0 END) AS NOCUMPLE1,
SUM (CASE WHEN MES_ACTUAL=1 AND ENE IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL1,
SUM (CASE WHEN MES_ACTUAL=1 AND FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN MES_ACTUAL=1 AND FEB='i' THEN 1 ELSE 0 END) AS NOCUMPLE2,
SUM (CASE WHEN MES_ACTUAL=1 AND FEB IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2,
SUM (CASE WHEN MES_ACTUAL=1 AND MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MES_ACTUAL=1 AND MAR='i' THEN 1 ELSE 0 END) AS NOCUMPLE3,
SUM (CASE WHEN MES_ACTUAL=1 AND MAR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3,
SUM (CASE WHEN MES_ACTUAL=1 AND ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN MES_ACTUAL=1 AND ABR='i' THEN 1 ELSE 0 END) AS NOCUMPLE4,
SUM (CASE WHEN MES_ACTUAL=1 AND ABR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4,
SUM (CASE WHEN MES_ACTUAL=1 AND MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MES_ACTUAL=1 AND MAY='i' THEN 1 ELSE 0 END) AS NOCUMPLE5,
SUM (CASE WHEN MES_ACTUAL=1 AND MAY IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5,
SUM (CASE WHEN MES_ACTUAL=1 AND JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN MES_ACTUAL=1 AND JUN='i' THEN 1 ELSE 0 END) AS NOCUMPLE6,
SUM (CASE WHEN MES_ACTUAL=1 AND JUN IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6,

SUM	(CASE WHEN MES_ACTUAL=2 AND ENE='p' THEN 1 ELSE 0 END) AS CUMPLE2_1,
SUM (CASE WHEN MES_ACTUAL=2 AND ENE='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_1,
SUM (CASE WHEN MES_ACTUAL=2 AND ENE IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_1,
SUM	(CASE WHEN MES_ACTUAL=2 AND FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2_2,
SUM (CASE WHEN MES_ACTUAL=2 AND FEB='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_2,
SUM (CASE WHEN MES_ACTUAL=2 AND FEB IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_2,
SUM	(CASE WHEN MES_ACTUAL=2 AND MAR='p' THEN 1 ELSE 0 END) AS CUMPLE2_3,
SUM (CASE WHEN MES_ACTUAL=2 AND MAR='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_3,
SUM (CASE WHEN MES_ACTUAL=2 AND MAR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_3,
SUM	(CASE WHEN MES_ACTUAL=2 AND ABR='p' THEN 1 ELSE 0 END) AS CUMPLE2_4,
SUM (CASE WHEN MES_ACTUAL=2 AND ABR='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_4,
SUM (CASE WHEN MES_ACTUAL=2 AND ABR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_4,
SUM	(CASE WHEN MES_ACTUAL=2 AND MAY='p' THEN 1 ELSE 0 END) AS CUMPLE2_5,
SUM (CASE WHEN MES_ACTUAL=2 AND MAY='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_5,
SUM (CASE WHEN MES_ACTUAL=2 AND MAY IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_5,
SUM	(CASE WHEN MES_ACTUAL=2 AND JUN='p' THEN 1 ELSE 0 END) AS CUMPLE2_6,
SUM (CASE WHEN MES_ACTUAL=2 AND JUN='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_6,
SUM (CASE WHEN MES_ACTUAL=2 AND JUN IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_6,

SUM	(CASE WHEN MES_ACTUAL=3 AND ENE='p' THEN 1 ELSE 0 END) AS CUMPLE3_1,
SUM (CASE WHEN MES_ACTUAL=3 AND ENE='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_1,
SUM (CASE WHEN MES_ACTUAL=3 AND ENE IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_1,
SUM	(CASE WHEN MES_ACTUAL=3 AND FEB='p' THEN 1 ELSE 0 END) AS CUMPLE3_2,
SUM (CASE WHEN MES_ACTUAL=3 AND FEB='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_2,
SUM (CASE WHEN MES_ACTUAL=3 AND FEB IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_2,
SUM	(CASE WHEN MES_ACTUAL=3 AND MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3_3,
SUM (CASE WHEN MES_ACTUAL=3 AND MAR='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_3,
SUM (CASE WHEN MES_ACTUAL=3 AND MAR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_3,
SUM	(CASE WHEN MES_ACTUAL=3 AND ABR='p' THEN 1 ELSE 0 END) AS CUMPLE3_4,
SUM (CASE WHEN MES_ACTUAL=3 AND ABR='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_4,
SUM (CASE WHEN MES_ACTUAL=3 AND ABR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_4,
SUM	(CASE WHEN MES_ACTUAL=3 AND MAY='p' THEN 1 ELSE 0 END) AS CUMPLE3_5,
SUM (CASE WHEN MES_ACTUAL=3 AND MAY='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_5,
SUM (CASE WHEN MES_ACTUAL=3 AND MAY IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_5,
SUM	(CASE WHEN MES_ACTUAL=3 AND JUN='p' THEN 1 ELSE 0 END) AS CUMPLE3_6,
SUM (CASE WHEN MES_ACTUAL=3 AND JUN='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_6,
SUM (CASE WHEN MES_ACTUAL=3 AND JUN IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_6,

SUM	(CASE WHEN MES_ACTUAL=4 AND ENE='p' THEN 1 ELSE 0 END) AS CUMPLE4_1,
SUM (CASE WHEN MES_ACTUAL=4 AND ENE='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_1,
SUM (CASE WHEN MES_ACTUAL=4 AND ENE IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_1,
SUM	(CASE WHEN MES_ACTUAL=4 AND FEB='p' THEN 1 ELSE 0 END) AS CUMPLE4_2,
SUM (CASE WHEN MES_ACTUAL=4 AND FEB='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_2,
SUM (CASE WHEN MES_ACTUAL=4 AND FEB IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_2,
SUM	(CASE WHEN MES_ACTUAL=4 AND MAR='p' THEN 1 ELSE 0 END) AS CUMPLE4_3,
SUM (CASE WHEN MES_ACTUAL=4 AND MAR='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_3,
SUM (CASE WHEN MES_ACTUAL=4 AND MAR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_3,
SUM	(CASE WHEN MES_ACTUAL=4 AND ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4_4,
SUM (CASE WHEN MES_ACTUAL=4 AND ABR='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_4,
SUM (CASE WHEN MES_ACTUAL=4 AND ABR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_4,
SUM	(CASE WHEN MES_ACTUAL=4 AND MAY='p' THEN 1 ELSE 0 END) AS CUMPLE4_5,
SUM (CASE WHEN MES_ACTUAL=4 AND MAY='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_5,
SUM (CASE WHEN MES_ACTUAL=4 AND MAY IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_5,
SUM	(CASE WHEN MES_ACTUAL=4 AND JUN='p' THEN 1 ELSE 0 END) AS CUMPLE4_6,
SUM (CASE WHEN MES_ACTUAL=4 AND JUN='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_6,
SUM (CASE WHEN MES_ACTUAL=4 AND JUN IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_6,

SUM	(CASE WHEN MES_ACTUAL=5 AND ENE='p' THEN 1 ELSE 0 END) AS CUMPLE5_1,
SUM (CASE WHEN MES_ACTUAL=5 AND ENE='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_1,
SUM (CASE WHEN MES_ACTUAL=5 AND ENE IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_1,
SUM	(CASE WHEN MES_ACTUAL=5 AND FEB='p' THEN 1 ELSE 0 END) AS CUMPLE5_2,
SUM (CASE WHEN MES_ACTUAL=5 AND FEB='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_2,
SUM (CASE WHEN MES_ACTUAL=5 AND FEB IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_2,
SUM	(CASE WHEN MES_ACTUAL=5 AND MAR='p' THEN 1 ELSE 0 END) AS CUMPLE5_3,
SUM (CASE WHEN MES_ACTUAL=5 AND MAR='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_3,
SUM (CASE WHEN MES_ACTUAL=5 AND MAR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_3,
SUM	(CASE WHEN MES_ACTUAL=5 AND ABR='p' THEN 1 ELSE 0 END) AS CUMPLE5_4,
SUM (CASE WHEN MES_ACTUAL=5 AND ABR='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_4,
SUM (CASE WHEN MES_ACTUAL=5 AND ABR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_4,
SUM	(CASE WHEN MES_ACTUAL=5 AND MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5_5,
SUM (CASE WHEN MES_ACTUAL=5 AND MAY='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_5,
SUM (CASE WHEN MES_ACTUAL=5 AND MAY IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_5,
SUM	(CASE WHEN MES_ACTUAL=5 AND JUN='p' THEN 1 ELSE 0 END) AS CUMPLE5_6,
SUM (CASE WHEN MES_ACTUAL=5 AND JUN='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_6,
SUM (CASE WHEN MES_ACTUAL=5 AND JUN IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_6,

SUM	(CASE WHEN MES_ACTUAL>=6 AND ENE='p' THEN 1 ELSE 0 END) AS CUMPLE6_1,
SUM (CASE WHEN MES_ACTUAL>=6 AND ENE='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_1,
SUM (CASE WHEN MES_ACTUAL>=6 AND ENE IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_1,
SUM	(CASE WHEN MES_ACTUAL>=6 AND FEB='p' THEN 1 ELSE 0 END) AS CUMPLE6_2,
SUM (CASE WHEN MES_ACTUAL>=6 AND FEB='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_2,
SUM (CASE WHEN MES_ACTUAL>=6 AND FEB IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_2,
SUM	(CASE WHEN MES_ACTUAL>=6 AND MAR='p' THEN 1 ELSE 0 END) AS CUMPLE6_3,
SUM (CASE WHEN MES_ACTUAL>=6 AND MAR='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_3,
SUM (CASE WHEN MES_ACTUAL>=6 AND MAR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_3,
SUM	(CASE WHEN MES_ACTUAL>=6 AND ABR='p' THEN 1 ELSE 0 END) AS CUMPLE6_4,
SUM (CASE WHEN MES_ACTUAL>=6 AND ABR='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_4,
SUM (CASE WHEN MES_ACTUAL>=6 AND ABR IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_4,
SUM	(CASE WHEN MES_ACTUAL>=6 AND MAY='p' THEN 1 ELSE 0 END) AS CUMPLE6_5,
SUM (CASE WHEN MES_ACTUAL>=6 AND MAY='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_5,
SUM (CASE WHEN MES_ACTUAL>=6 AND MAY IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_5,
SUM	(CASE WHEN MES_ACTUAL>=6 AND JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6_6,
SUM (CASE WHEN MES_ACTUAL>=6 AND JUN='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_6,
SUM (CASE WHEN MES_ACTUAL>=6 AND JUN IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_6
INTO MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO
GROUP BY DESC_VTA ORDER BY DESC_VTA


/*
SELECT DESC_VTA,SUM (CASE WHEN MES_ACTUAL=1 AND JUL='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN MES_ACTUAL=1 AND JUL='i' THEN 1 ELSE 0 END) AS NOCUMPLE1,
SUM (CASE WHEN MES_ACTUAL=1 AND JUL IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL1,
SUM (CASE WHEN MES_ACTUAL=1 AND AGO='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN MES_ACTUAL=1 AND AGO='i' THEN 1 ELSE 0 END) AS NOCUMPLE2,
SUM (CASE WHEN MES_ACTUAL=1 AND AGO IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2,
SUM (CASE WHEN MES_ACTUAL=1 AND SEP='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MES_ACTUAL=1 AND SEP='i' THEN 1 ELSE 0 END) AS NOCUMPLE3,
SUM (CASE WHEN MES_ACTUAL=1 AND SEP IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3,
SUM (CASE WHEN MES_ACTUAL=1 AND OCT='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN MES_ACTUAL=1 AND OCT='i' THEN 1 ELSE 0 END) AS NOCUMPLE4,
SUM (CASE WHEN MES_ACTUAL=1 AND OCT IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4,
SUM (CASE WHEN MES_ACTUAL=1 AND NOV='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MES_ACTUAL=1 AND NOV='i' THEN 1 ELSE 0 END) AS NOCUMPLE5,
SUM (CASE WHEN MES_ACTUAL=1 AND NOV IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5,
SUM (CASE WHEN MES_ACTUAL=1 AND DIC='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN MES_ACTUAL=1 AND DIC='i' THEN 1 ELSE 0 END) AS NOCUMPLE6,
SUM (CASE WHEN MES_ACTUAL=1 AND DIC IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6,

SUM	(CASE WHEN MES_ACTUAL=2 AND JUL='p' THEN 1 ELSE 0 END) AS CUMPLE2_1,
SUM (CASE WHEN MES_ACTUAL=2 AND JUL='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_1,
SUM (CASE WHEN MES_ACTUAL=2 AND JUL IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_1,
SUM	(CASE WHEN MES_ACTUAL=2 AND AGO='p' THEN 1 ELSE 0 END) AS CUMPLE2_2,
SUM (CASE WHEN MES_ACTUAL=2 AND AGO='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_2,
SUM (CASE WHEN MES_ACTUAL=2 AND AGO IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_2,
SUM	(CASE WHEN MES_ACTUAL=2 AND SEP='p' THEN 1 ELSE 0 END) AS CUMPLE2_3,
SUM (CASE WHEN MES_ACTUAL=2 AND SEP='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_3,
SUM (CASE WHEN MES_ACTUAL=2 AND SEP IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_3,
SUM	(CASE WHEN MES_ACTUAL=2 AND OCT='p' THEN 1 ELSE 0 END) AS CUMPLE2_4,
SUM (CASE WHEN MES_ACTUAL=2 AND OCT='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_4,
SUM (CASE WHEN MES_ACTUAL=2 AND OCT IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_4,
SUM	(CASE WHEN MES_ACTUAL=2 AND NOV='p' THEN 1 ELSE 0 END) AS CUMPLE2_5,
SUM (CASE WHEN MES_ACTUAL=2 AND NOV='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_5,
SUM (CASE WHEN MES_ACTUAL=2 AND NOV IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_5,
SUM	(CASE WHEN MES_ACTUAL=2 AND DIC='p' THEN 1 ELSE 0 END) AS CUMPLE2_6,
SUM (CASE WHEN MES_ACTUAL=2 AND DIC='i' THEN 1 ELSE 0 END) AS NOCUMPLE2_6,
SUM (CASE WHEN MES_ACTUAL=2 AND DIC IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL2_6,

SUM	(CASE WHEN MES_ACTUAL=3 AND JUL='p' THEN 1 ELSE 0 END) AS CUMPLE3_1,
SUM (CASE WHEN MES_ACTUAL=3 AND JUL='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_1,
SUM (CASE WHEN MES_ACTUAL=3 AND JUL IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_1,
SUM	(CASE WHEN MES_ACTUAL=3 AND AGO='p' THEN 1 ELSE 0 END) AS CUMPLE3_2,
SUM (CASE WHEN MES_ACTUAL=3 AND AGO='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_2,
SUM (CASE WHEN MES_ACTUAL=3 AND AGO IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_2,
SUM	(CASE WHEN MES_ACTUAL=3 AND SEP='p' THEN 1 ELSE 0 END) AS CUMPLE3_3,
SUM (CASE WHEN MES_ACTUAL=3 AND SEP='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_3,
SUM (CASE WHEN MES_ACTUAL=3 AND SEP IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_3,
SUM	(CASE WHEN MES_ACTUAL=3 AND OCT='p' THEN 1 ELSE 0 END) AS CUMPLE3_4,
SUM (CASE WHEN MES_ACTUAL=3 AND OCT='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_4,
SUM (CASE WHEN MES_ACTUAL=3 AND OCT IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_4,
SUM	(CASE WHEN MES_ACTUAL=3 AND NOV='p' THEN 1 ELSE 0 END) AS CUMPLE3_5,
SUM (CASE WHEN MES_ACTUAL=3 AND NOV='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_5,
SUM (CASE WHEN MES_ACTUAL=3 AND NOV IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_5,
SUM	(CASE WHEN MES_ACTUAL=3 AND DIC='p' THEN 1 ELSE 0 END) AS CUMPLE3_6,
SUM (CASE WHEN MES_ACTUAL=3 AND DIC='i' THEN 1 ELSE 0 END) AS NOCUMPLE3_6,
SUM (CASE WHEN MES_ACTUAL=3 AND DIC IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL3_6,

SUM	(CASE WHEN MES_ACTUAL=4 AND JUL='p' THEN 1 ELSE 0 END) AS CUMPLE4_1,
SUM (CASE WHEN MES_ACTUAL=4 AND JUL='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_1,
SUM (CASE WHEN MES_ACTUAL=4 AND JUL IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_1,
SUM	(CASE WHEN MES_ACTUAL=4 AND AGO='p' THEN 1 ELSE 0 END) AS CUMPLE4_2,
SUM (CASE WHEN MES_ACTUAL=4 AND AGO='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_2,
SUM (CASE WHEN MES_ACTUAL=4 AND AGO IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_2,
SUM	(CASE WHEN MES_ACTUAL=4 AND SEP='p' THEN 1 ELSE 0 END) AS CUMPLE4_3,
SUM (CASE WHEN MES_ACTUAL=4 AND SEP='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_3,
SUM (CASE WHEN MES_ACTUAL=4 AND SEP IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_3,
SUM	(CASE WHEN MES_ACTUAL=4 AND OCT='p' THEN 1 ELSE 0 END) AS CUMPLE4_4,
SUM (CASE WHEN MES_ACTUAL=4 AND OCT='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_4,
SUM (CASE WHEN MES_ACTUAL=4 AND OCT IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_4,
SUM	(CASE WHEN MES_ACTUAL=4 AND NOV='p' THEN 1 ELSE 0 END) AS CUMPLE4_5,
SUM (CASE WHEN MES_ACTUAL=4 AND NOV='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_5,
SUM (CASE WHEN MES_ACTUAL=4 AND NOV IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_5,
SUM	(CASE WHEN MES_ACTUAL=4 AND DIC='p' THEN 1 ELSE 0 END) AS CUMPLE4_6,
SUM (CASE WHEN MES_ACTUAL=4 AND DIC='i' THEN 1 ELSE 0 END) AS NOCUMPLE4_6,
SUM (CASE WHEN MES_ACTUAL=4 AND DIC IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL4_6,

SUM	(CASE WHEN MES_ACTUAL=5 AND JUL='p' THEN 1 ELSE 0 END) AS CUMPLE5_1,
SUM (CASE WHEN MES_ACTUAL=5 AND JUL='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_1,
SUM (CASE WHEN MES_ACTUAL=5 AND JUL IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_1,
SUM	(CASE WHEN MES_ACTUAL=5 AND AGO='p' THEN 1 ELSE 0 END) AS CUMPLE5_2,
SUM (CASE WHEN MES_ACTUAL=5 AND AGO='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_2,
SUM (CASE WHEN MES_ACTUAL=5 AND AGO IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_2,
SUM	(CASE WHEN MES_ACTUAL=5 AND SEP='p' THEN 1 ELSE 0 END) AS CUMPLE5_3,
SUM (CASE WHEN MES_ACTUAL=5 AND SEP='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_3,
SUM (CASE WHEN MES_ACTUAL=5 AND SEP IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_3,
SUM	(CASE WHEN MES_ACTUAL=5 AND OCT='p' THEN 1 ELSE 0 END) AS CUMPLE5_4,
SUM (CASE WHEN MES_ACTUAL=5 AND OCT='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_4,
SUM (CASE WHEN MES_ACTUAL=5 AND OCT IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_4,
SUM	(CASE WHEN MES_ACTUAL=5 AND NOV='p' THEN 1 ELSE 0 END) AS CUMPLE5_5,
SUM (CASE WHEN MES_ACTUAL=5 AND NOV='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_5,
SUM (CASE WHEN MES_ACTUAL=5 AND NOV IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_5,
SUM	(CASE WHEN MES_ACTUAL=5 AND DIC='p' THEN 1 ELSE 0 END) AS CUMPLE5_6,
SUM (CASE WHEN MES_ACTUAL=5 AND DIC='i' THEN 1 ELSE 0 END) AS NOCUMPLE5_6,
SUM (CASE WHEN MES_ACTUAL=5 AND DIC IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL5_6,

SUM	(CASE WHEN MES_ACTUAL>=6 AND JUL='p' THEN 1 ELSE 0 END) AS CUMPLE6_1,
SUM (CASE WHEN MES_ACTUAL>=6 AND JUL='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_1,
SUM (CASE WHEN MES_ACTUAL>=6 AND JUL IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_1,
SUM	(CASE WHEN MES_ACTUAL>=6 AND AGO='p' THEN 1 ELSE 0 END) AS CUMPLE6_2,
SUM (CASE WHEN MES_ACTUAL>=6 AND AGO='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_2,
SUM (CASE WHEN MES_ACTUAL>=6 AND AGO IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_2,
SUM	(CASE WHEN MES_ACTUAL>=6 AND SEP='p' THEN 1 ELSE 0 END) AS CUMPLE6_3,
SUM (CASE WHEN MES_ACTUAL>=6 AND SEP='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_3,
SUM (CASE WHEN MES_ACTUAL>=6 AND SEP IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_3,
SUM	(CASE WHEN MES_ACTUAL>=6 AND OCT='p' THEN 1 ELSE 0 END) AS CUMPLE6_4,
SUM (CASE WHEN MES_ACTUAL>=6 AND OCT='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_4,
SUM (CASE WHEN MES_ACTUAL>=6 AND OCT IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_4,
SUM	(CASE WHEN MES_ACTUAL>=6 AND NOV='p' THEN 1 ELSE 0 END) AS CUMPLE6_5,
SUM (CASE WHEN MES_ACTUAL>=6 AND NOV='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_5,
SUM (CASE WHEN MES_ACTUAL>=6 AND NOV IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_5,
SUM	(CASE WHEN MES_ACTUAL>=6 AND DIC='p' THEN 1 ELSE 0 END) AS CUMPLE6_6,
SUM (CASE WHEN MES_ACTUAL>=6 AND DIC='i' THEN 1 ELSE 0 END) AS NOCUMPLE6_6,
SUM (CASE WHEN MES_ACTUAL>=6 AND DIC IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL6_6
INTO MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO
GROUP BY DESC_VTA ORDER BY DESC_VTA
*/



SELECT DESC_VTA,
SUM (CASE WHEN MES_ACTUAL>=1 AND ([1] ='p') THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN MES_ACTUAL>=1 AND ([1] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE1,
SUM (CASE WHEN MES_ACTUAL>=1 AND ([1] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL1,
SUM (CASE WHEN MES_ACTUAL>=2 AND ([2] ='p') THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN MES_ACTUAL>=2 AND ([2] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE2,
SUM (CASE WHEN MES_ACTUAL>=2 AND ([2] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL2,
SUM (CASE WHEN MES_ACTUAL>=3 AND ([3] ='p') THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MES_ACTUAL>=3 AND ([3] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE3,
SUM (CASE WHEN MES_ACTUAL>=3 AND ([3] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL3,
SUM (CASE WHEN MES_ACTUAL>=4 AND ([4] ='p') THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN MES_ACTUAL>=4 AND ([4] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE4,
SUM (CASE WHEN MES_ACTUAL>=4 AND ([4] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL4,
SUM (CASE WHEN MES_ACTUAL>=5 AND ([5] ='p') THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MES_ACTUAL>=5 AND ([5] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE5,
SUM (CASE WHEN MES_ACTUAL>=5 AND ([5] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL5,
SUM (CASE WHEN MES_ACTUAL>=6 AND ([6] ='p') THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN MES_ACTUAL>=6 AND ([6] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE6,
SUM (CASE WHEN MES_ACTUAL>=6 AND ([6] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL6
INTO MESES_ACUMULADOS_EFEC
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO GROUP BY DESC_VTA ORDER BY DESC_VTA

/*************************************/
/***********TOTALES POR MES***********/
/*
SELECT DESC_VTA,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6

INTO DIR_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO GROUP BY DESC_VTA ORDER BY DESC_VTA


SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO FUNCI_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN
ORDER BY DESC_VTA,DESC_OFNA,DESC_GEREN


SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_MAT,RAZ_SOCIAL,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO MAT_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 
GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_MAT,RAZ_SOCIAL ORDER BY DESC_VTA


SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_SUC,PROM_MAT,NOMBRE_SUC,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO SUC_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 
GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_SUC,PROM_MAT,NOMBRE_SUC ORDER BY DESC_VTA


SELECT DESC_VTA,DESC_OFNA,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO OFNA_MES_A_MES_TA
FROM DETALLE_PARA_OFNA 
GROUP BY DESC_VTA,DESC_OFNA ORDER BY DESC_VTA

*/

SELECT DESC_VTA,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE7,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE7,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE8,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE8,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE9,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE9,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE10,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE10,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE11,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE11,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE12,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE12
INTO DIR_ACUMULAD_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO GROUP BY DESC_VTA ORDER BY DESC_VTA


SELECT DESC_VTA,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO DIR_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO GROUP BY DESC_VTA ORDER BY DESC_VTA

/*
SELECT DESC_VTA,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO DIR_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO GROUP BY DESC_VTA ORDER BY DESC_VTA
*/


SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO FUNCI_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN
ORDER BY DESC_VTA,DESC_OFNA,DESC_GEREN


/*
SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO FUNCI_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN
ORDER BY DESC_VTA,DESC_OFNA,DESC_GEREN
*/

SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE7,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE7,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE8,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE8,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE9,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE9,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE10,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE10,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE11,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE11,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE12,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE12
INTO FUNCI_ACUM_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN
ORDER BY DESC_VTA,DESC_OFNA,DESC_GEREN


SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_MAT,RAZ_SOCIAL,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
COUNT(NUM_AGENTE) AS AGENTES
INTO MAT_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 
GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_MAT,RAZ_SOCIAL ORDER BY DESC_VTA


/*
SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_MAT,RAZ_SOCIAL,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
COUNT(NUM_AGENTE) AS AGENTES
INTO MAT_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 
GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_MAT,RAZ_SOCIAL ORDER BY DESC_VTA
*/

/*SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_MAT,RAZ_SOCIAL,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE7,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE7,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE8,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE8,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE9,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE9,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE10,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE10,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE11,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE11,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE12,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE12,
COUNT(NUM_AGENTE) AS AGENTES
INTO MAT_ACUM_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 
GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_MAT,RAZ_SOCIAL ORDER BY DESC_VTA*/

SELECT B.DESC_VTA,A.PROM_MAT,A.RAZ_SOCIAL,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE7,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE7,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE8,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE8,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE9,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE9,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE10,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE10,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE11,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE11,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE12,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE12,
COUNT(NUM_AGENTE) AS AGENTES
INTO MAT_ACUM_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO A INNER JOIN CATALOGO B ON A.PROM_MAT=B.PROM_SUC AND B.Proceso=@fec_proc
GROUP BY B.DESC_VTA,A.PROM_MAT,A.RAZ_SOCIAL ORDER BY B.DESC_VTA


SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_SUC,PROM_MAT,NOMBRE_SUC,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE7,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE7,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE8,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE8,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE9,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE9,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE10,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE10,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE11,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE11,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE12,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE12
INTO SUC_ACUM_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 
GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_SUC,PROM_MAT,NOMBRE_SUC ORDER BY DESC_VTA


/*
SELECT DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_SUC,PROM_MAT,NOMBRE_SUC,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO SUC_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 
GROUP BY DESC_VTA,DESC_OFNA,DESC_GEREN,PROM_SUC,PROM_MAT,NOMBRE_SUC ORDER BY DESC_VTA
*/


SELECT B.DESC_VTA,A.PROM_SUC,A.PROM_MAT,A.NOMBRE_SUC,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO SUC_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO A INNER JOIN CATALOGO B ON A.PROM_SUC=B.PROM_SUC
GROUP BY B.DESC_VTA,A.PROM_SUC,A.PROM_MAT,A.NOMBRE_SUC ORDER BY A.PROM_SUC


/*
SELECT B.DESC_VTA,A.PROM_SUC,A.PROM_MAT,A.NOMBRE_SUC,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
INTO SUC_MES_A_MES_TA
FROM DETALLE_EFECTIVIDAD_REPORTE_UNO A INNER JOIN CATALOGO B ON A.PROM_SUC=B.PROM_SUC
GROUP BY B.DESC_VTA,A.PROM_SUC,A.PROM_MAT,A.NOMBRE_SUC ORDER BY A.PROM_SUC
*/

SELECT DESC_VTA,DESC_OFNA,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE7,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE7,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE8,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE8,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE9,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE9,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE10,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE10,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE11,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE11,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE12,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE12,
COUNT(NUM_AGENTE) AS AGENTES
INTO OFNA_ACUM_TA
FROM DETALLE_PARA_OFNA 
GROUP BY DESC_VTA,DESC_OFNA ORDER BY DESC_VTA


SELECT DESC_VTA,DESC_OFNA,
SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
COUNT(NUM_AGENTE) AS AGENTES
INTO OFNA_MES_A_MES_TA
FROM DETALLE_PARA_OFNA 
GROUP BY DESC_VTA,DESC_OFNA ORDER BY DESC_VTA


/*
SELECT DESC_VTA,DESC_OFNA,
SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE1,
SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE2,
SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE3,
SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE4,
SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE5,
SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE6,
SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6,
COUNT(NUM_AGENTE) AS AGENTES
INTO OFNA_MES_A_MES_TA
FROM DETALLE_PARA_OFNA 
GROUP BY DESC_VTA,DESC_OFNA ORDER BY DESC_VTA
*/

/*RESP_GEREN_AGENCIA*/
	SELECT A.DESC_VTA,B.DESC_OFNA,B.DESC_GEREN, B.RESP_GEREN,
	SUM (CASE WHEN MES_ACTUAL>=1 AND ([1] ='p') THEN 1 ELSE 0 END) AS CUMPLE1,
	SUM (CASE WHEN MES_ACTUAL>=1 AND ([1] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE1,
	SUM (CASE WHEN MES_ACTUAL>=1 AND ([1] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL1,
	SUM (CASE WHEN MES_ACTUAL>=2 AND ([2] ='p') THEN 1 ELSE 0 END) AS CUMPLE2,
	SUM (CASE WHEN MES_ACTUAL>=2 AND ([2] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE2,
	SUM (CASE WHEN MES_ACTUAL>=2 AND ([2] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL2,
	SUM (CASE WHEN MES_ACTUAL>=3 AND ([3] ='p') THEN 1 ELSE 0 END) AS CUMPLE3,
	SUM (CASE WHEN MES_ACTUAL>=3 AND ([3] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE3,
	SUM (CASE WHEN MES_ACTUAL>=3 AND ([3] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL3,
	SUM (CASE WHEN MES_ACTUAL>=4 AND ([4] ='p') THEN 1 ELSE 0 END) AS CUMPLE4,
	SUM (CASE WHEN MES_ACTUAL>=4 AND ([4] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE4,
	SUM (CASE WHEN MES_ACTUAL>=4 AND ([4] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL4,
	SUM (CASE WHEN MES_ACTUAL>=5 AND ([5] ='p') THEN 1 ELSE 0 END) AS CUMPLE5,
	SUM (CASE WHEN MES_ACTUAL>=5 AND ([5] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE5,
	SUM (CASE WHEN MES_ACTUAL>=5 AND ([5] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL5,
	SUM (CASE WHEN MES_ACTUAL>=6 AND ([6] ='p') THEN 1 ELSE 0 END) AS CUMPLE6,
	SUM (CASE WHEN MES_ACTUAL>=6 AND ([6] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE6,
	SUM (CASE WHEN MES_ACTUAL>=6 AND ([6] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL6 
	INTO P_RESP_GEREN
	FROM DETALLE_EFECTIVIDAD_REPORTE_UNO A INNER JOIN CATALOGO B ON A.PROM_SUC=B.PROM_SUC AND B.Proceso=1702 
	WHERE A.DESC_VTA LIKE '%Z%' GROUP BY A.DESC_VTA,B.DESC_OFNA,B.DESC_GEREN, B.RESP_GEREN ORDER BY DESC_VTA
	
	/*RESP_GERE2_AGENCIA*/
	SELECT A.DESC_VTA,B.DESC_OFNA,B.DESC_GEREN, B.RESP_GERE2,
	SUM (CASE WHEN MES_ACTUAL>=1 AND ([1] ='p') THEN 1 ELSE 0 END) AS CUMPLE1,
	SUM (CASE WHEN MES_ACTUAL>=1 AND ([1] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE1,
	SUM (CASE WHEN MES_ACTUAL>=1 AND ([1] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL1,
	SUM (CASE WHEN MES_ACTUAL>=2 AND ([2] ='p') THEN 1 ELSE 0 END) AS CUMPLE2,
	SUM (CASE WHEN MES_ACTUAL>=2 AND ([2] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE2,
	SUM (CASE WHEN MES_ACTUAL>=2 AND ([2] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL2,
	SUM (CASE WHEN MES_ACTUAL>=3 AND ([3] ='p') THEN 1 ELSE 0 END) AS CUMPLE3,
	SUM (CASE WHEN MES_ACTUAL>=3 AND ([3] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE3,
	SUM (CASE WHEN MES_ACTUAL>=3 AND ([3] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL3,
	SUM (CASE WHEN MES_ACTUAL>=4 AND ([4] ='p') THEN 1 ELSE 0 END) AS CUMPLE4,
	SUM (CASE WHEN MES_ACTUAL>=4 AND ([4] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE4,
	SUM (CASE WHEN MES_ACTUAL>=4 AND ([4] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL4,
	SUM (CASE WHEN MES_ACTUAL>=5 AND ([5] ='p') THEN 1 ELSE 0 END) AS CUMPLE5,
	SUM (CASE WHEN MES_ACTUAL>=5 AND ([5] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE5,
	SUM (CASE WHEN MES_ACTUAL>=5 AND ([5] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL5,
	SUM (CASE WHEN MES_ACTUAL>=6 AND ([6] ='p') THEN 1 ELSE 0 END) AS CUMPLE6,
	SUM (CASE WHEN MES_ACTUAL>=6 AND ([6] ='i') THEN 1 ELSE 0 END) AS NOCUMPLE6,
	SUM (CASE WHEN MES_ACTUAL>=6 AND ([6] IS NOT NULL) THEN 1 ELSE 0 END) AS TOTAL6 
	INTO P_RESP_GERE2
	FROM DETALLE_EFECTIVIDAD_REPORTE_UNO A INNER JOIN CATALOGO B ON A.PROM_SUC=B.PROM_SUC AND B.Proceso=1702 
	WHERE A.DESC_VTA LIKE '%Z%' GROUP BY A.DESC_VTA,B.DESC_OFNA,B.DESC_GEREN, B.RESP_GERE2 ORDER BY DESC_VTA

	/*EDAS*/
	
	SELECT DESC_VTA,EDA,
	SUM (CASE WHEN ENE='p' THEN 1 ELSE 0 END) AS CUMPLE1,
	SUM (CASE WHEN ENE='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
	SUM (CASE WHEN FEB='p' THEN 1 ELSE 0 END) AS CUMPLE2,
	SUM (CASE WHEN FEB='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
	SUM (CASE WHEN MAR='p' THEN 1 ELSE 0 END) AS CUMPLE3,
	SUM (CASE WHEN MAR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
	SUM (CASE WHEN ABR='p' THEN 1 ELSE 0 END) AS CUMPLE4,
	SUM (CASE WHEN ABR='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
	SUM (CASE WHEN MAY='p' THEN 1 ELSE 0 END) AS CUMPLE5,
	SUM (CASE WHEN MAY='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
	SUM (CASE WHEN JUN='p' THEN 1 ELSE 0 END) AS CUMPLE6,
	SUM (CASE WHEN JUN='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
	INTO EDAS_SEMESTRE
	FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 
	GROUP BY DESC_VTA,EDA ORDER BY DESC_VTA
	
	/*
	SELECT DESC_VTA,EDA,
	SUM (CASE WHEN JUL='p' THEN 1 ELSE 0 END) AS CUMPLE1,
	SUM (CASE WHEN JUL='i' THEN 1 ELSE 0 END) AS NO_CUMPLE1,
	SUM (CASE WHEN AGO='p' THEN 1 ELSE 0 END) AS CUMPLE2,
	SUM (CASE WHEN AGO='i' THEN 1 ELSE 0 END) AS NO_CUMPLE2,
	SUM (CASE WHEN SEP='p' THEN 1 ELSE 0 END) AS CUMPLE3,
	SUM (CASE WHEN SEP='i' THEN 1 ELSE 0 END) AS NO_CUMPLE3,
	SUM (CASE WHEN OCT='p' THEN 1 ELSE 0 END) AS CUMPLE4,
	SUM (CASE WHEN OCT='i' THEN 1 ELSE 0 END) AS NO_CUMPLE4,
	SUM (CASE WHEN NOV='p' THEN 1 ELSE 0 END) AS CUMPLE5,
	SUM (CASE WHEN NOV='i' THEN 1 ELSE 0 END) AS NO_CUMPLE5,
	SUM (CASE WHEN DIC='p' THEN 1 ELSE 0 END) AS CUMPLE6,
	SUM (CASE WHEN DIC='i' THEN 1 ELSE 0 END) AS NO_CUMPLE6
	INTO EDAS_SEMESTRE
	FROM DETALLE_EFECTIVIDAD_REPORTE_UNO 
	GROUP BY DESC_VTA,EDA ORDER BY DESC_VTA
	*/